### ISSUE TITLE
DbgModelClientEx.h IDataModelManager4, IDeconstructableConcept  and IFilteredNamespacePropertyToken Don't Exist

### ISSUE THREAD

**Issue by trustednstaller** [Microsoft/WinDbg-Libraries#15]
The `IDataModelManager4 ` and `IDeconstructableConcept` COM interfaces do not exist anywhere and the client library cannot compile.  I have to replace the manager with the only existing version (2) inside `DbgModel.h` and completely comment out the `IDeconstructableConcept` code in the client to get it to compile.  Would be great to get this fixed asap since it makes the client library unusable. 

Thanks!

**Comment by trustednstaller** [comment]
Any updates here?  Can't be a difficult fix and again, crucially, `DbgModelClientEx.h` is unusable  in its current state.

**Comment by lzybkr** [comment]
You can find the latest version of DbgModel.h in a nuget package [here](https://www.nuget.org/packages/Microsoft.Debugging.Platform.DbgEng). I just checked and it does define both `IDataModelManager4` and `IDeconstrutableConcept`.

**Comment by trustednstaller** [comment]
Thanks!  Can close the issue.  Guess it is time to accept Nuget here on my end :)

**Comment by yangrongwei** [comment]
Mm, how to use the DbgModel.h  from nuget package from [here](https://www.nuget.org/packages/Microsoft.Debugging.Platform.DbgEng) ?

I am using Visual Studio 2022 Preview. After install the nuget, my project is still using <DbgModel.h> from SDK.

I have tried my best to solve the problem by myself, but I do not know how to use the head from 

`packages\Microsoft.Debugging.Platform.DbgEng.20230731.1609.0\build\native\inc`

Gentlemans, please help. I used many hours on this _problem_.  Thanks!

**Comment by lzybkr** [comment]
> I am using Visual Studio 2022 Preview. After install the nuget, my project is still using <DbgModel.h> from SDK.

You will need to check your [INCLUDE path](https://learn.microsoft.com/en-us/cpp/build/working-with-project-properties?view=msvc-170). The path is searched in the order specified, so to ensure you pick up the version you want, you must ensure the nuget location appears before the SDK path.
