### ISSUE TITLE
Is there are a extension for stl?

### ISSUE THREAD

**Issue by 18Fl** [Microsoft/WinDbg-Libraries#18]
Hello, When I use windbg, I found dump the content about stl is often make me pain. like std::map. I guess !std_map and !stl maybe could help me a little, But seems its is been deprecated, so is there another plan for this(etc, extension or command..). Thx.

- https://learn.microsoft.com/en-us/windows-hardware/drivers/debuggercmds/-stl

**Comment by wmessmer-msft** [comment]
WinDbg ships with the same NatVis visualizers for STL that are included with Visual Studio.  These visualizations should be visible in the locals/watch window of the new UI (not WinDbg classic) or via the **dx command** (both the new UI and WinDbg classic).
