### ISSUE TITLE
The CPP sample fails to compile with VS 2019 tools (142)

### ISSUE THREAD

**Issue by zodiacon** [Microsoft/WinDbg-Libraries#2]
The call to Details::ExtractString fails to compile, but it does compile if "Details" is removed.
Also bad_alloc is not found

**Comment by glitchnsec** [comment]
@zodiacon see [Unable to build SimpleIntroClientLibrary (Cpp) #15 on WinDbg-Samples](https://github.com/microsoft/WinDbg-Samples/issues/15). @robmikh proposed a [solution](https://github.com/microsoft/WinDbg-Samples/issues/15#issue-596297809) to bad_alloc and I proposed a [solution](https://github.com/microsoft/WinDbg-Samples/issues/15#issuecomment-633028477) for the ExtractString issue.

What do you think?

**Comment by zodiacon** [comment]
I think the solution is good enough.
I still feel there is a compiler bug here. My solution was (about the ExtractString) is to remove the "details::" prefix. But it doesn't make sense, since in VS 2017 tools it fails to compile.
I like the "moving eariler" solution better.

**Comment by glitchnsec** [comment]
Thanks @zodiacon. In a bit, I'll make a PR but it seems these repositories aren't monitored.
