### ISSUE TITLE
Constructing a TypeSignature by signature and module name does not work as expected

### ISSUE THREAD

**Issue by AlanAtWork** [Microsoft/WinDbg-Libraries#8]
I found that my `TypeSignatureExtension` extension model was not matching the type successfully when constructed with the signature and module name. This overload is calling `IDebugHostSymbols::CreateTypeSignatureForModuleRange` and passing nullptr for the minimum and maximum version parameters. Though that call succeeds I don't think the actual signature is valid, at least it is not matching as expected.

The expectation seems to be that calling `CreateTypeSignatureForModuleRange` but not providing a version range should produce an equivalent signature object to calling `IDebugHostSymbols::CreateTypeSignature` with the signature and an `IDebugHostModule*`. The documentation for [CreateTypeSignatureForModuleRange](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dbgmodel/nf-dbgmodel-idebughostsymbols-createtypesignatureformodulerange) and the referenced [CreateModuleSignature](https://docs.microsoft.com/en-us/windows-hardware/drivers/ddi/dbgmodel/nf-dbgmodel-idebughostsymbols-createmodulesignature) suggest that this should work. Could this be a bug in DbgModel?

If I update the constructor to first get the `IDebugHostModule` using `IDebugHostSymbols::FindModuleByName` and pass that to `CreateTypeSignature`, everything works as expected.

The referenced constructor overload:
```
// TypeSignature(signature, moduleName)
//
// Creates a type signature for a type whose name and module name matches the supplied string signatures.
//
template<typename TStr1, typename TStr2,
    typename = std::enable_if_t<!std::is_same_v<typename std::decay_t<TStr2>, Module>>>
    TypeSignature(_In_ TStr1&& signature, _In_ TStr2&& moduleName)
{
    const wchar_t *pSignature = Details::ExtractString(signature);
    const wchar_t *pModuleName = Details::ExtractString(moduleName);
    ComPtr<IDebugHostSymbols> spHostSym;
    ClientEx::CheckHr(ClientEx::GetHost()->QueryInterface(IID_PPV_ARGS(&spHostSym)));
    ClientEx::CheckHr(spHostSym->CreateTypeSignatureForModuleRange(pSignature, 
        pModuleName, 
        nullptr,
        nullptr,
        &m_spTypeSignature));
}
```

**Comment by wmessmer-msft** [comment]
Apologies for the delay in response.

FindModuleByName() will allow the passed module name to be either the module's real image name (e.g.: foo.dll) or the one that you can reference it by in the debugger engine (e.g.: foo  or foo_<hex_base>).  The module name passed to the various CreateTypeSignature functions will only accept the module's real image name (e.g.: foo.dll).  That's an inconsistency that should probably be looked at within the data model itself (and thank you for the report).  That said -- it's not a bug in the OSS helper library.

I'll also note that there's a distinct difference between the two cases you mention:

1) Calling CreateTypeSignatureForModuleRange and passing a name/nullptr/nullptr will create a signature that will match any module that matches that name of any version.

2) Calling FindModuleByName and then CreateTypeSignature with that module will create a signature that will match ONLY the particular instance of the module passed to it.  In other words, if there's two copies of something loaded (e.g.: ntdll in a 32-bit process running on 64-bit Windows), this one would only match the specific instance passed.  It would also no longer match if that DLL were unloaded and reloaded.  It's literally tied to a specific instance of a module as known by the debugger.

**Comment by AlanAtWork** [comment]
Ok, I see. That's a fairly subtle difference that could probably use some doc on IDebugHostSymbols.

Thank you for the clarification!

**Comment by DOMARS** [comment]
@wmessmer-msft, I will add this text to the remarks section of the FindModuleByName, CreateTypeSignatureForModuleRange and the CreateTypeSignature topics.

**Differences in symbol module matching in FindModuleByName, CreateTypeSignature and CreateTypeSignatureForModuleRange**

FindModuleByName() will allow the passed module name to be either the module's real image name for example My Module.dll, or the one that you can reference it by in the debugger engine (e.g.: MyModule or MyModule_<hex_base>). 

Calling CreateTypeSignatureForModuleRange and passing a name/nullptr/nullptr will create a signature that will match any module that matches that name of any version.

The module name passed to the CreateTypeSignature functions will only accept the module's real image name (e.g.: MyModule.dll). 

Calling FindModuleByName and then CreateTypeSignature with that module will create a signature that will match only the particular instance of the module passed to it. If there's two copies of a module that is loaded (e.g.: ntdll in a 32-bit process running on 64-bit Windows), it would only match the specific instance passed. It would also no longer match if that DLL were unloaded and reloaded. The signature is associated to a specific instance of a module as known by the debugger.
